version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: oldphone-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - oldphone-dev-network

volumes:
  redis_data:

networks:
  oldphone-dev-network:
    driver: bridge 