@echo off
echo Starting Redis with Docker Compose...
docker-compose -f docker-compose.dev.yml up -d redis

echo Waiting for Redis to be ready...
timeout /t 3 /nobreak > nul

echo Starting OldPhone Web application...
dotnet run --project .

echo Stopping Redis...
docker-compose -f docker-compose.dev.yml down 